pagopa/pagopa-payment-wallet-event-dispatcher-service

- .github/workflows/codeql.yml
> feat: use config file for codeql instead of managed config

- .devops/azure-templates/chart-current-version.yml
- .devops/azure-templates/gradle-github-release.yml
- .devops/azure-templates/helm-microservice-chart-deploy.yml
- build.gradle.kts
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-uat.yaml
- src/main/kotlin/it/pagopa/wallet/eventdispatcher/WalletEventDispatcherApplication.kt
* add missing azure devops templates
> fix(deploy): add missing azure devops templates

- gradle/verification-metadata.xml
Add javadoc and sources jars as trusted in dependency verifications metadata
Add javadoc and sources jars as trusted in dependency verifications metadata
> fix(gradle.lockfile): add javadoc and sources as trusted jars

- helm/values-uat.yaml
> fix: Wrong UAT keyvault name

- .devops/pay-wallet-code-review-pipelines.yml
- .devops/pay-wallet-deploy-pipelines.yml
> feat(pay-wallet): add pipeline for pay-wallet

- .devops/pay-wallet-deploy-pipelines.yml
- helm/pay-wallet-values-dev.yaml
- helm/pay-wallet-values-uat.yaml
> feat(pay-wallet): CHK-2928 add helm value for pay-wallet

- README.md
- helm/pay-wallet-values-dev.yaml
- helm/pay-wallet-values-uat.yaml
- helm/values-dev.yaml
- helm/values-uat.yaml
- src/main/kotlin/it/pagopa/wallet/eventdispatcher/common/serialization/WalletEventMixin.kt
- src/main/kotlin/it/pagopa/wallet/eventdispatcher/configuration/QueueConsumerConfiguration.kt
- src/main/kotlin/it/pagopa/wallet/eventdispatcher/configuration/SerializationConfiguration.kt
- src/main/kotlin/it/pagopa/wallet/eventdispatcher/domain/WalletEvent.kt
- src/main/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletExpirationQueueConsumer.kt
- src/main/kotlin/it/pagopa/wallet/eventdispatcher/queues/commons.kt
- src/main/resources/application.properties
- src/test/kotlin/it/pagopa/wallet/eventdispatcher/common/serialization/WalletEventMixinTest.kt
- src/test/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletExpirationQueueConsumerTest.kt
- src/test/kotlin/it/pagopa/wallet/eventdispatcher/queues/WalletUsageQueueConsumerTest.kt
- src/test/resources/application.properties
Add mocked implementation for wallet-expiration-queue event consumer.
This PR implements event consumer along with event parsing logic.
This handler will handle all wallet expiration events and perform compensation operation for all of those wallet that will be in a non-final status
> feat(wallet-expiration): configure azure storage queue event consumer

- helm/pay-wallet-values-dev.yaml
- helm/pay-wallet-values-uat.yaml
The goal of this PR is to add affinity in helm value in order to deploy payment-wallet service only on pay-wallet dedicated nodepool (create in this PR https://github.com/pagopa/pagopa-infra/pull/2141).
> feat(values): CHK-2948 add affinity to select pay-wallet nodepool

- helm/pay-wallet-values-dev.yaml
- helm/pay-wallet-values-uat.yaml
> Chk 2948 select nodepool

- .devops/pay-wallet-deploy-pipelines.yml
- helm/pay-wallet-values-prod.yaml
The goal of this PR is to add pipeline and helm value to deploy in PROD.
> feat(pipeline): CHK-2946 Add pipeline for prod

- helm/pay-wallet-values-prod.yaml
Align helm Italy north helm values
Align helm Italy north helm values
> chore(helm-itn): align itn env

- helm/pay-wallet-values-prod.yaml
- helm/pay-wallet-values-uat.yaml
Fix helm values for UAT and PROD itn env removing space from queue name
Fix helm values for UAT and PROD itn env removing space from queue name
> fix(helm): remove space for queue name

- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
- helm/values-dev.yaml
- helm/values-uat.yaml
Comment out WEU pipelines and helm values
The env to be used will be italy north only
> chore(weu to itn): comment out deploy and helm values

- helm/pay-wallet-values-prod.yaml
> Set at least 3 replicas for PROD env

- helm/pay-wallet-values-prod.yaml
> fix(ingress): delete .prod in ingress endpoint

- helm/pay-wallet-values-dev.yaml
- helm/pay-wallet-values-prod.yaml
- helm/pay-wallet-values-uat.yaml
> fix: [CHK-2982] Enabled spring integration otel

- helm/pay-wallet-values-uat.yaml
> feat(helm): Enabled blue deployment for uat environment

- docker-compose.yml
- add kafka in docker-compose
- create new topic `payment-wallet-injection-topic` (to rename in the future)
The goal of this PR is to add Kafka to the docker-compose setup, enabling testing for future developments that will require integration with Azure Event Hub.
```
docker-compose up
```
check the following log
```
Creating kafka topics
Created topic my-topic-1.
Created topic my-topic-2.
Successfully created the following topics:
payment-wallet-injection-topic
```
> chore: CHK-3328 add kafka to local develop

- .github/workflows/deploy.yml
> fix(deploy-workflow): fix azure pipeline name

- helm/pay-wallet-values-prod.yaml
Changed the prod env configuration to a less performant and stressful one
This is the change to apply once the high throughput of the first implant process has ended
> chore(config): update prod env

- helm/pay-wallet-values-uat.yaml
Fix UAT ingress value
Fix UAT ingress value
> fix: ingress value for uat env

- helm/pay-wallet-values-prod.yaml
Tune up PROD values after zero downtime pipeline deploy.
There are the following modification/improvements:
1. set service to QOS burstable for CPU increasing cpu limit to 900 millicore
2. lowered initial delay timeout to 30 seconds as per point 1
3. explicitate `RollingUpdate` strategy to perform a complete pod substitution
4. introduce stabilization window to scale up 
5. set application logging level to INFO for prod deployment
Those modification are needed after PROD deployment with the `zero downtime deployment strategy` pipeline upgrade to make deployment as smooth as possible
> fix(prod deployment): tune up prod deployment values

- gradle.properties
Increase gradle max heap size to be used for deamon agent during build
CodeQL analysis failed because of OOM error caused by insufficient default heap size memory.
CodeQL analysis run (see PR checks section)
> chore: increase gradle heap size

- .devops/pay-wallet-code-review-pipelines.yml
- updated versions for pipeline tasks which generated deprecation warnings on remote build and deploy processes
This update was needed to prevent future execution failures on code review and deploy pipelines
> [PIDM-41] chore(azdo-pipeline-tasks): update tasks versions

- helm/pay-wallet-values-dev.yaml
> chore(helm-dev): Update elk config dev

- helm/pay-wallet-values-uat.yaml
Update UAT OTEL collector endpoint
Update UAT OTEL collector endpoint
expected)
> chore(OTEL): update collector endpoint

- helm/pay-wallet-values-uat.yaml
Fix OTLP exporter protocol to GRPC
Fix OTLP exporter protocol to GRPC
expected)
> fix: OTEL protocol

- helm/pay-wallet-values-prod.yaml
- Changed references and protocol used for OTEL
This change permits to point to Telemetry directly via K8s Service, also changing used protocol.
> [PIDM-275] fix: changing OTEL endpoint and protocol

- helm/pay-wallet-values-dev.yaml
- helm/pay-wallet-values-uat.yaml
> [PIDM-826] feat(redis): migrate to standard redis

- README.md
> chore: trigger deploy action
